repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13  # Use the latest version from: https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
        # args: [--fix]  # run autofix for linting issues
      - id: ruff-format
